emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/{emitter-name}"
    # file-type: ""                                       # Type: string, Options: [yaml, json], Description: If the content should be serialized as YAML or JSON. Default 'yaml', it not specified infer from the `output-file` extension
    # output-file: ""                                     # Type: string, Description: Name of the output file.
    #                                                     #  Output file will interpolate the following values:
    #                                                     #   - service-name: Name of the service
    #                                                     #   - service-name-if-multiple: Name of the service if multiple
    #                                                     #   - version: Version of the service if multiple
    #                                                     # 
    #                                                     #  Default: `{service-name-if-multiple}.{version}.openapi.yaml` or `.json` if `file-type` is `"json"`
    #                                                     # 
    #                                                     #  Example Single service no versioning
    #                                                     #   - `openapi.yaml`
    #                                                     # 
    #                                                     #  Example Multiple services no versioning
    #                                                     #   - `openapi.Org1.Service1.yaml`
    #                                                     #   - `openapi.Org1.Service2.yaml`
    #                                                     # 
    #                                                     #  Example Single service with versioning
    #                                                     #   - `openapi.v1.yaml`
    #                                                     #   - `openapi.v2.yaml`
    #                                                     # 
    #                                                     #  Example Multiple service with versioning
    #                                                     #   - `openapi.Org1.Service1.v1.yaml`
    #                                                     #   - `openapi.Org1.Service1.v2.yaml`
    #                                                     #   - `openapi.Org1.Service2.v1.0.yaml`
    #                                                     #   - `openapi.Org1.Service2.v1.1.yaml`    
    # openapi-versions: []                                # Type: array
    # new-line: lf                                        # Type: string, Options: [crlf, lf], Description: Set the newline character for emitting files.
    # omit-unreachable-types: false                       # Type: boolean, Description: Omit unreachable types.
    #                                                     # By default all types declared under the service namespace will be included. With this flag on only types references in an operation will be emitted.
    # include-x-typespec-name: never                      # Type: string, Options: [inline-only, never], Description: If the generated openapi types should have the `x-typespec-name` extension set with the name of the TypeSpec type that created it.
    #                                                     # This extension is meant for debugging and should not be depended on.
    # safeint-strategy: int64                             # Type: string, Options: [double-int, int64], Description: How to handle safeint type. Options are:
    #                                                     #  - `double-int`: Will produce `type: integer, format: double-int`
    #                                                     #  - `int64`: Will produce `type: integer, format: int64`
    #                                                     # 
    #                                                     # Default: `int64`
    # seal-object-schemas: false                          # Type: boolean, Description: If true, then for models emitted as object schemas we default `additionalProperties` to false for
    #                                                     # OpenAPI 3.0, and `unevaluatedProperties` to false for OpenAPI 3.1, if not explicitly specified elsewhere.
    #                                                     # Default: `false`
    # experimental-parameter-examples: ""                 # Type: string, Options: [data, serialized], Description: Determines how to emit examples on parameters.
    #                                                     # Note: This is an experimental feature and may change in future versions.
    #                                                     # See https://spec.openapis.org/oas/v3.0.4.html#style-examples for parameter example serialization rules
    #                                                     # See https://github.com/OAI/OpenAPI-Specification/discussions/4622 for discussion on handling parameter examples.
    # operation-id-strategy: undefined                    # 
